name: CI

on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]
  merge_group:

jobs:
  ci:
    uses: danielriddell21/github-actions/.github/workflows/ci.yaml@v1
    permissions:
      contents: write
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
      tag-token: ${{ secrets.VIVARIUM_TOKEN }}
